spring:
  application:
    name: ms-hhrr-users
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /v1
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8666/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}