spring:
  application:
    name: ms-hhrr-edge-service
server:
  port: 8999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8666/eureka/
zuul:
  routes:
    ms-hhrr-areas:
      service-id: ms-hhrr-areas
      path: /api/hhrr/areas/**
    ms-hhrr-employees:
      service-id: ms-hhrr-employees
      path: /api/hhrr/employees/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 5000
