spring:
  application:
    name: ms-hhrr-edge-service

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    ms-human-resources-areas:
      service-id: ms-hhrr-areas
      path: /api/hhrr/areas/**
    ms-human-resources-employees:
      service-id: ms-hhrr-employees
      path: /api/hhrr/employees/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 5000
