server:
  servlet:
    context-path: /v1
  port: 8081
spring:
  application:
    name: ms-hhrr-areas
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: hr
    password: hrpw
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8666/eureka/
