spring:
  application:
    name: ms-hhrr-employees
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: hr
    password: hrpw
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect

server:
  servlet:
    context-path: /ms-hhrr-employees/v1
  port: ${PORT:0}

api:
  support:
    ms-human-resources-areas:
      url: http://localhost:43823/ms-hhrr-areas/v1

#ms-human-resources-areas:
#  ribbon:
#    listOfServers: localhost:9001, localhost:9002

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 5000

# mvn clean package spring-boot:run -Dspring-boot.run.arguments=--server.port=9001
# mvn spring-boot:run -Dspring-boot.run.arguments=--server.port=9002
# mvn spring-boot:run -Dspring-boot.run.profiles=prod
